### ISSUE TITLE
Workitem (git tf wi) is lost on pull

### ISSUE THREAD

**Issue by GojaN** [nodirt/git-tf#11]
When a commit is marked with a workitem with `git tf wi` the note that's hold the value is lost because is not copied to the new commit created as consequence of the rebase that happen in `git tf pull`

To fix this issue the value for the config variable [_notes.rewriteRef_](http://www.kernel.org/pub/software/scm/git/docs/git-notes.html) must be setup with the value _refs/notes/tf_
I test this fix and works fine. I'm not sure what is the correct way to set this value so I create this issue.

Regards

**Comment by nodirt** [comment]
Fixed in `git-tf-clone` 12e58eeae85355adb921adfb15fc3796b664eeca, merged into dev.

With an existing repository just run

``` bash
$ git config notes.rewrite.rebase true
```

**Comment by nodirt** [comment]
For some reason I didn't see your second paragraph. Added the rewriteRef: 0af39fe

``` bash
$ git config notes.rewriteRef notes/ref/tf*
```

**Comment by GojaN** [comment]
Can you read the complete description of the issue?

Any way, are you sure that the set notes.rewrite.rebase to true fix the issue? In the man page of [git notes](http://www.kernel.org/pub/software/scm/git/docs/git-notes.html) the description of _notes.rewrite_ says:

_"`notes.rewrite.<command>`
When rewriting commits with <command> (currently amend or rebase), if this variable is false, git will not copy notes from the original to the rewritten commit. **Defaults to true**. See also "notes.rewriteRef" below."_

And for "notes.rewriteRef" the man says:

_"`notes.rewriteRef`
When copying notes during a rewrite, specifies the (fully qualified) ref whose notes should be copied. May be a glob, in which case notes in all matching refs will be copied. You may also specify this configuration several times._

_Does not have a default value; **you must configure this variable to enable note rewriting**._

_Can be overridden with the GIT_NOTES_REWRITE_REF environment variable."_

I can reproduce the issue and I fix it only setting the _notes.reqriteRef_ value. May be you already have this value configured for some reason.

**Comment by nodirt** [comment]
In the [second comment](#issuecomment-6691659) above I pointed out to commit 0af39feeda948f38d0017c86faced84cbe029ef5 that sets `notes.rewriteRef` to `refs/notes/tf*` which is glob and includes `tf.wi`. Isn't it what you ask for?

Making sure that `notes.rewrite.rebase` is true is also necessary.

I'm not sure setting `GIT_NOTES_REWRITE_REF` on the git-tf startup is a good idea because a developer may want to make rewriteRef less selective (e.g. `*`).

**Comment by GojaN** [comment]
Ups!, my bad. Didn't see your second commit.
I will test this today, if every thing works fine I close this issue.

Thanks you very much.
